version: 2
updates:
  - package-ecosystem: "gradle"
    directories:
      - "/"
      - "/modules/apps"
      - "/modules/dxp/apps"
      - "/modules/private/apps"
      - "/modules/util"
      - "/modules/test"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directories:
      - "/"
      - "/modules"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directories:
      - "/modules/frontend"
      - "/modules/apps/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
